### ISSUE TITLE
Load baseline with Famix  only if the image do not contain moose

### ISSUE THREAD

**Issue by mahugnon** [moosetechnology/FamixReplication#2]
It should load famix only if not exist in the image. For example, if Famix is already loaded, the baseline load famix anyway.  In my case, it loads famix twice. Which slowdown my builds

**Comment by jecisc** [comment]
There is a baseline of replication without famix.

Since replication depends on famix but is also a dependency of Moose (which contains famix), I cannot do the usual famix loading trick explained in the wiki.
